

--新建一个MOD
local Hui=GameMain:NewMod("Unlockallbuilding")

--进入游戏后
function Hui:OnEnter()

    -- 自然景物 
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QiShi1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiZhongQiShi1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QiShi2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiZhongQiShi2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QiShi3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiZhongQiShi3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QiShi4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiZhongQiShi4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QiShi5")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiZhongQiShi5")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QiShi6")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiZhongQiShi6")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LingShu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LingShu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LingShu3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LingShu4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LingShu5")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LingShu6")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ZiXiaoJuShu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShaShenMu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShaShenMu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShaShenMu3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShaShenMu4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiShenHuaShu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiShenHuaShu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiShenHuaShu3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_TaoShu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_TaoShu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_TaoShu3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuShu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuShu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuShu3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuShu4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuShu5")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuShu6")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_CongRong1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_CongRong2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuShouHai1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuShouHai2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuShouHai3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuShouHai4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LuoTuoCao")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShiCheJu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShiCheJu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShiCheJu3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_GuMu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_GuMu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_GuMu3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_GuMu4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_GuMu5")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_GuMu6")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuCanJi1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuCanJi2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuCanJi3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuCanJi4")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShangGuCanJi5")
    --人工建筑 
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LingDiShuiChi")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LianFaTan")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_TaiXuanBingZhu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Build_KunLunFang")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QingTongLong")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QingTongShouXiangLu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QingTongFanQi")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YanDiTai")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_JuXingXiangLu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_TengLongZhu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_HuangLongDengTai")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LianHuaDengTai")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuHeQingLian1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuHeQingLian2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YuHeQingLian3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_JianYiFuDiao")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_XiaoDanLu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_XiaoDanLu2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_HuoDing")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShuiLianTai")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_XieXiDeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_KuLouDeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Build_BaiManFang")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_DiMuJiDeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_DiMuJiQi")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_DiMuMiXue")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QiShaJianZhu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_XieLongDiaoXiang")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_XiongKuiDeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShaZhang1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ShaZhang2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_QingShaDeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_BingFengDiaoSu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_DiMuKuiShou")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_MoMenJiQi")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_MoMenJiQi1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_MoZhuaDiaoSu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_MoWenHuaPing")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_KuLouHuaPing")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_XiePingFeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YaoHuoPen")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ChangMingDeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_JuXingShouGu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_LongXingYuanPan")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YaoZuDiaoXiang")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YaoShouDing")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Build_WanYaoMen")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_TianSheQi")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_YaoZuXingJia")

    --武当DLC 弯曲墙
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallDownLeftS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallUpLeftS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallMidUpS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallMidRightS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallVerticalS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallVerticalHalfS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallHorizontalS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallDownLeftTinyS")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallUpLeftTinyS")


    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("ZhenWuCarve")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("TurTleMonu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("IncenseTripod")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallDownLeft")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallDownLeft2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallUpLeft")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallUpLeft2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallMidUp")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallMidUp2")


    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallMidRight")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallMidRight2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallVertical")

    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallVerticalHalf")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallHorizontalHalf")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallHorizontal")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallDownLeftTiny")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallUpLeftTiny")



    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallGate")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("RedWallDrum")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangBigGate")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangScreen")

    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangFlag")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangXiangLu")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangPuTuan")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangXianHeDeng")

    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangDivine")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WuDangXuanWuDeng")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ChaShu1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_ChaShu2")


    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_WuDangSong1")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_WuDangSong2")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_WuDangSong3")
    CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Building_WuDangSong4")


    -- CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("YaoRoof")
    -- CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("WoodRoof_SpringFestival")
    -- CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("StoneRoof_SpringFestival")

    -- CS.XiaWorld.SchoolMgr.Instance:UnLockBuilding("Door_WanYao")

end



